### ISSUE TITLE
Inserir informação do ano no banner rotativo

### ISSUE THREAD

**Issue by pgrangeiro** [pythonsudeste/pythonsudeste2017-site#6]
Inserir informação do ano no banner rotativo no topo do site
![captura de tela de 2016-11-17 00-21-10](https://cloud.githubusercontent.com/assets/2524981/20373840/ce8aa6d8-ac5b-11e6-90de-3a923d0d4d34.png)

**Comment by cassiobotaro** [comment]
Corrigido em 13b2050
