### ISSUE TITLE
Consertar info de duração do evento

### ISSUE THREAD

**Issue by pgrangeiro** [pythonsudeste/pythonsudeste2017-site#7]
Consertar a info de duração do evento na coluna sobre a conferência. Serão 3 dias (5 à 7 de maio) e não 2.
![captura de tela de 2016-11-17 00-22-14](https://cloud.githubusercontent.com/assets/2524981/20373870/077b21ca-ac5c-11e6-8cc1-bb039bbf23ad.png)

**Comment by cassiobotaro** [comment]
Corrigido em    d44bcd3
